import {StyleSheet, Dimensions} from 'react-native';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#ffffff',
    },
    screenContainer: {
      flex: 1,
      position: 'relative',
      paddingHorizontal: 16,
      backgroundColor: '#ffffff',
    },
    profileContainer: {
      position: 'relative',
      paddingTop: 16,
      marginTop: 239,
      backgroundColor: '#ffffff',
      borderTopLeftRadius: 25,
      borderTopRightRadius: 25,
      alignItems: 'center',
    },
    logOut: {
      position: 'absolute',
      top: 20,
      left: 150,
    },
    imageBG:{
      flex: 1,
      resizeMode: 'contain',
      justifyContent: 'flex-end',
    },
    avatar: {
      position: 'relative',
      marginTop: -60,
      width: 120,
      height: 120,
      borderRadius: 16,
      backgroundColor: '#D3D3D3',
    },
    user: {
      position: 'absolute',
      bottom: 20,
      right: -13,
      width: 25,
      height: 25,
      borderRadius: 50,
    },
    userBox: {
      flexDirection: 'row',
      height: 60,
      alignItems: 'center',
      marginBottom: 8,
    },
    userBoxOfComment: {
      width: 28,
      height: 28,
    },
    title: {
      marginVertical: 32,
      fontSize: 30,
      lineHeight: 35,
      textAlign: 'center',
    },
    form: {
      paddingHorizontal: 16,
      backgroundColor: '#ffffff',
      borderTopLeftRadius: 25,
      borderTopRightRadius: 25,
    },
    image: {
      alignSelf: 'center',
      resizeMode: 'contain',
      width: '100%',
      height: '100%',
      borderRadius: 8,
    },
    icon: {
      width: 40,
      height: 40,
      padding: 8,
    },
    plusIcon: {
      width: 70,
      height: 40,
    },
    inputAuth: {
      padding: 16,
      marginBottom: 16,
      width: '100%',
      fontSize: 16,
      height: 50,
      borderWidth: 1,
      borderColor: '#E8E8E8',
      backgroundColor: '#F6F6F6',
      borderRadius: 8,
    },
    input: {
      padding: 16,
      marginBottom: 16,
      width: '100%',
      fontSize: 16,
      height: 50,
      borderWidth: 1,
      borderColor: 'transparent',
      borderBottomColor: '#E8E8E8',
    },
    password: {
      position: 'relative',
      width: '100%',
    },
    showPassword: {
      position: 'absolute',
      top: 12,
      right: 25,
    },
    showBtn: {
      color: '#1B4371',
    },
    comment: {
      position: 'relative',
      width: '100%',
    },
    sendIcon: {
      position: 'absolute',
      top: 8,
      right: 0,
    },
    text: {
      color: '#000000',
      fontSize: 16,
      textAlign: 'center',
    },
    btn: {
      marginTop: 19,
      marginBottom: 16,
      paddingVertical: 16,
      paddingHorizontal: 32,
      width: '100%',
      borderRadius: 100,
    },
    camera: {
      position: 'relative',
      height: 240,
      marginTop: 16,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 8,
    },
    takePhotoView: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      borderWidth: 2,
      borderRadius: 8,
      borderColor: '#ffffff',
      width: '30%',
      height: '30%',
    },
    snapContainer: {
      position: 'absolute',
      justifyContent: 'center',
      alignItems: 'center',
      width: 60,
      height: 60,
      borderRadius: 50,
      backgroundColor: '#ffffff',
    },
    snap: {
      width: 24,
      height: 24,
    },
    trashIcon: {
      marginHorizontal: 'auto',
      width: 70,
      height: 40,
      backgroundColor: '#F6F6F6',
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    postIconContainer: {
      position: 'relative',
      flexDirection: 'row',
      alignItems: 'center',
    },
    postIconLocation: {
      position: 'absolute',
      top: 12,
      left: 10,
    },
    postIcon: {
      width: 24,
      height: 24,
    },
    infoPost: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    map: {
      width: Dimensions.get("window").width,
      height: Dimensions.get("window").height,
    },
});